name = "zariski_spaces"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ZariskiSpaces"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"